/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ScannerRouteImport } from './routes/scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/consultation': typeof ConsultationRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/consultation': typeof ConsultationRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/consultation': typeof ConsultationRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anatomy'
    | '/consultation'
    | '/login'
    | '/maps'
    | '/profile'
    | '/register'
    | '/reminders'
    | '/scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anatomy'
    | '/consultation'
    | '/login'
    | '/maps'
    | '/profile'
    | '/register'
    | '/reminders'
    | '/scanner'
  id:
    | '__root__'
    | '/'
    | '/anatomy'
    | '/consultation'
    | '/login'
    | '/maps'
    | '/profile'
    | '/register'
    | '/reminders'
    | '/scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnatomyRoute: typeof AnatomyRoute
  ConsultationRoute: typeof ConsultationRoute
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  ScannerRoute: typeof ScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnatomyRoute: AnatomyRoute,
  ConsultationRoute: ConsultationRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  ScannerRoute: ScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
